title: Usando o Portal do Desenvolvedor
hide: false
nav:
  - index.md
  - Gerenciar a Conta Sudo: sudo.md
  - Enviar Atualizações do Runtime: upgrade.md
  - Ativar Modo de Manutenção: maintenance.md
  - Pausar Transações: pause-transactions.md
  - Personificar Contas: impersonate.md
  - Emitir Tokens: minting.md
  - EVM Inteligente - Lista Branca de Implantações de Contratos: smart-contracts-creation-filter.md