title: Utilisation du portail développeur
hide: false
nav:
- index.md
- Gérer le compte Sudo: sudo.md
- Déployer des mises à jour du runtime: upgrade.md
- Activer le mode maintenance: maintenance.md
- Mettre les transactions en pause: pause-transactions.md
- Usurper des comptes: impersonate.md
- Frapper des tokens: minting.md
- EVM intelligent - Liste blanche des déploiements de contrats: smart-contracts-creation-filter.md
