title: Estrutura de Desenvolvimento de Rede
hide: false
nav:
  - index.md
  - Visão Geral: overview.md
  - Arquitetura do Framework: architecture.md
  - Modularidade: modules.md
  # - 'Native Cross-Chain Communication': 'xcm.md'
