title: Using the Tanssi dApp
hide: false
nav:
  - index.md
  - 'Block Production Services Payment': 'services-payment.md'
  - 'Manage Tokens': 'manage-tokens.md'
  # - 'Manage Cross-Chain Communication Channels': 'xcm-channels.md'
  # - 'Register External Assets': 'register-external-assets.md'
