title: Onboarding
hide: false
nav:
  - index.md
  - run-an-operator
  - 'Registrar no Symbiotic': 'register-in-symbiotic.md'
  - 'Optar Pelo Tanssi': 'opt-in-to-tanssi.md'
  - 'Configurar Sua Conta': 'account-setup.md'