title: Using the Developer Portal
hide: false
nav:
  - index.md
  - 'Manage the Sudo Account': 'sudo.md'
  - 'Dispatch Runtime Upgrades': 'upgrade.md'
  - 'Enable Maintenance Mode': 'maintenance.md'
  - 'Pause Transactions': 'pause-transactions.md'
  - 'Impersonate Accounts': 'impersonate.md'
  - 'Mint Tokens': 'minting.md'
  - 'Smart EVM - Whitelist Contract Deployments': 'smart-contracts-creation-filter.md'

