nav:
    - index.md
    - pt/builders
    - pt/node-operators
    - pt/learn
    - pt/ai-resources
    - Sobre:
        - 'Sobre Tanssi': https://www.tanssi.network/
        - 'TestNet do Tanssi': https://apps.tanssi.network/create
