nav:
  - index.md
  - 404.md
  - 'Builders': pt/builders
  - 'Node Operators': pt/node-operators
  - 'Aprender': pt/learn
  - 'Recursos de IA': pt/ai-resources
  - 'Sobre':
    - 'Sobre Tanssi': https://www.tanssi.network/
    - 'TestNet da Tanssi': https://apps.tanssi.network/create

