title: Incorporación
hide: false
nav:
  - index.md
  - 'Ejecutar un operador': run-an-operator
  - 'Registrarse en Symbiotic': register-in-symbiotic.md
  - 'Unirse a Tanssi': opt-in-to-tanssi.md
  - 'Configurar tu cuenta': account-setup.md
