title: Precompiles
hide: false
nav:
  - index.md
  - 'Batch': batch.md
  - 'Call Permit': call-permit.md
  - 'Token nativo ERC-20': erc20.md
  # - 'Cross Chain Transfers': cross-chain-transfers.md
  # - 'External Assets as ERC-20': external-assets-erc20.md
  - 'Proxy': proxy.md
