title: Redes alimentadas por Tanssi
hide: false
nav:
  - index.md
  - Visão geral: overview.md
  - Modelos incluídos: included-templates.md
  - Funcionalidades principais do runtime: runtime-features.md
  - Taxas de transação: tx-fees.md
