title: Uso del portal para desarrolladores
hide: false
nav:
- index.md
- Gestionar la cuenta Sudo: sudo.md
- Enviar actualizaciones de runtime: upgrade.md
- Habilitar modo de mantenimiento: maintenance.md
- Pausar transacciones: pause-transactions.md
- Suplantar cuentas: impersonate.md
- Emitir tokens: minting.md
- EVM inteligente - Lista blanca de despliegues de contratos: smart-contracts-creation-filter.md
